### ISSUE TITLE
ID problems running your script with my shiny container

### ISSUE THREAD

**Issue by TomHarrop** [vsoch/singularity-shiny#1]
Thanks for this super helpful script!

I'm trying to set up my own shiny container to work without modifications to your script, but I'm running into an ID or permissions issue.

When I run it as-is with my container, I get the following error:

```
[2018-07-17T03:12:43.488] [ERROR] shiny-server - Error loading config: The user 'rstudio' does not have permissions to run applications as one of the users in 'docker'. Please restart shiny-server as one of the users in  'docker'. (/etc/shiny-server/shiny-server.conf:1:1)
```

I've managed to get around this by changing `run_as docker;` to `run_as rstudio;` in the `shiny-server.conf` file, **after** running `prepare_template.sh start`,  and then it works fine.

I also tried adding `adduser --disabled-password --gecos "" --ingroup shiny docker` to my `$post`, but that gave me the same error.

My Singularity file is here: https://github.com/TomHarrop/singularity-containers/blob/master/tools/Singularity.shinotate_1.5.8.918

Built version here if it helps: https://www.singularity-hub.org/collections/996

I would appreciate any tips in getting my container set up properly!

**Comment by vsoch** [comment]
hey @TomHarrop ! I think the idea is that the user running shiny is expected to change (e.g., you mention you get around it by changing the user). If this is the case and it works fine, what is the issue?

**Comment by TomHarrop** [comment]
Ok, I can run it like that - thanks

**Comment by vsoch** [comment]
Would it be helpful / useful to you to have another argument to have this "run_as" variable able to set programatically? I can definitely do that!

**Comment by vsoch** [comment]
hey @TomHarrop take a look here https://github.com/vsoch/singularity-shiny/pull/2 and let me know if this change helps you to generate the correct configuration!

**Comment by TomHarrop** [comment]
Awesome! I just tested it and it works. Thanks again for your work on this.

**Comment by vsoch** [comment]
fantastic! I will merge then. Thanks for testing it out, and apologies I didn't jump on the fix first thing. :frog:
