### ISSUE TITLE
Custom logs folder missing logs and lib folder

### ISSUE THREAD

**Issue by paulklemm** [vsoch/singularity-shiny#7]
Setting a custom `--logs` folder to an empty folder will crash the shiny server on startup, because it expects a `logs` and `lib` folder in there.

These are created when `--logs` is not set:

```bash
    # Temporary directory, if doesn't exist
    if [ ! -d "${SHINY_LOGS}" ]; then
        mkdir -p ${SHINY_LOGS}/logs;
        mkdir -p ${SHINY_LOGS}/lib;
    fi
```

https://github.com/vsoch/singularity-shiny/blob/c6d105590869bda906cad630962ad3f227aca397/prepare_template.sh#L148

The easiest solution would be removing the `if` statement, but I don't know if that's breaks some use-cases for you.

With removed `if` statements it works just fine.

**Comment by vsoch** [comment]
Could you tell me more about your use case? The intention is that the shiny server is provided already in the container, and if you have customizations you bind to that folder, e.g., this note:

> For custom applications, also add --bind $SHINY_BASE:/srv/shiny-server
    To see your applications, open your browser to http://127.0.0.1:$SHINY_PORT or
    open a ssh connection from your computer to your cluster.

If you remove the shiny base and the logs it's just using the entire thing as a shell, and you don't really need it to begin with.

**Comment by vsoch** [comment]
And notice in the Singularity recipe the permissions issue is also handled on `%post` I think you need to:

 - not change the SHINY_BASE
 - bind at runtime to your application

**Comment by vsoch** [comment]
And how can you provide a logs folder that doesn't exist and we aren't allowed to make? That isn't logical. What are you trying to do instead?

**Comment by paulklemm** [comment]
Sorry for being unclear, I'm still new to Singularity.

My use-case is rather simple, I want to spawn a shiny server on our HPC cluster and point both the `base` folder with all the shiny applications as well as the `logs` folder to my working directory.

For example:

- `logs`: `/beegfs/scratch/pklemm/shiny/logs`
- `base`: `/beegfs/scratch/pklemm/shiny/base`

Both folders already exist, I created them beforehand. EDIT: Both of them are also empty, hence the problem with the missing `logs`/`lib` folder

It works fine as long as I also create the folders `/beegfs/scratch/pklemm/shiny/logs/logs` and `/beegfs/scratch/pklemm/shiny/logs/libs`, otherwise starting up the Singularity container fails.

**Comment by vsoch** [comment]
ahh okay! So why not just bind those locations at runtime? Can you show me the command you are (currently) running?

**Comment by vsoch** [comment]
The fix would probably be to have the folders created (in the %runscript) section if they don't exist.

**Comment by paulklemm** [comment]
Sorry I'll have to pick this discussion up again on Monday. Thanks for the super-fast help so far.

Creating the folders in the `%runscript` is a good idea.

**Comment by vsoch** [comment]
ok sounds good!

**Comment by paulklemm** [comment]
I think creating the folders in the `%runscript` folder is the proper approach, but this makes the creation of the folders here obsolete:

https://github.com/vsoch/singularity-shiny/blob/c6d105590869bda906cad630962ad3f227aca397/prepare_template.sh#L148

This whole section in the `%runscript` section should look like this:

```bash
# Create required folders if they are missing
if [ ! -d "${SHINY_LOGS}/logs" ]; then
    mkdir -p ${SHINY_LOGS}/logs;
fi
if [ ! -d "${SHINY_LOGS}/lib" ]; then
    mkdir -p ${SHINY_LOGS}/lib;
fi
```

**Comment by vsoch** [comment]
Well, to step back a second, if you don't define the logs, it defaults to a directory in tmp, this line:

```bash
SHINY_LOGS=$(mktemp -d /tmp/shiny-server.XXXXXX) && rmdir ${SHINY_LOGS};
```
And that is so the directory can be made (on the host) in advance, and we can be sure that the directory location is writable because it's in tmp (/tmp is bound by default). 

I guess I don't see why, if you don't define the folder in advance (and let it default to tmp) and then you bind your /beegfs/scratch/pklemm/shiny/logs to the /tmp locations that have been created, this doesn't work for you? Why is it that when you run the script to generate the template (and the nginx configuration that correctly points to the logs) you are unable to create folders in /tmp?

**Comment by vsoch** [comment]
For example, if you want your logs folder different after generating the container, if it spits out that:

```bash
logs: /tmp/shiny-server.gG1X2Z
```
And you truly don't want it there, you can just bind that location to somewhere else:

```bash
--bind /somewhere/else:/tmp/shiny-server.gG1X2Z
```
I would say it wouldn't hurt to add the creation in the `%runscript` too, but it's also a viable use case to create the folders when you generate the template (and then not specify a different one). Would that satisfy your use case? If not, please describe how you are generating the configuration and trying to run it.

**Comment by paulklemm** [comment]
> I would say it wouldn't hurt to add the creation in the `%runscript` too, but it's also a viable use case to create the folders when you generate the template (and then not specify a different one). Would that satisfy your use case? If not, please describe how you are generating the configuration and trying to run it.

Oh you're totally right, I did not consider that use-case where you want to create the folders on generating the template.

Yes, generating the folders in the `%runscript` section would fix my problems. I can write a PR if you agree.

> I guess I don't see why, if you don't define the folder in advance (and let it default to tmp) and then you bind your /beegfs/scratch/pklemm/shiny/logs to the /tmp locations that have been created, this doesn't work for you? Why is it that when you run the script to generate the template (and the nginx configuration that correctly points to the logs) you are unable to create folders in /tmp?

I surely could do that, but my personal preference is to have the base and logs in one location without binding the folders to `/tmp`. Is that a bad practice?

**Comment by vsoch** [comment]
hey check out this PR!

https://github.com/vsoch/singularity-shiny/pull/8
It doesn't seem logical (now that I think of it) to generate the folders in the runscript - how do we know what folder has been chosen for logging? We don't. The issn't isn't within the container, it's on the host. To resolve this, I just removed the if statement - mkdir -p will not spit out an error if the directory already exists, and that way you can be sure the directories are generated. Please give it a try and let me know if it works for you.

Definitely not bad practice, just different than I originally intended.

**Comment by paulklemm** [comment]
PR #8 works fine for me!

**Comment by paulklemm** [comment]
Thank you so much for your help🤗

**Comment by vsoch** [comment]
You've so very welcome!! :smile:
